kubeprod/pkg/aks/cmd.go, kubeprod/pkg/aks/platform.go, kubeprod/pkg/aks/types.go, kubeprod/pkg/gke/cmd.go, kubeprod/pkg/gke/platform.go, kubeprod/pkg/gke/types.go, manifests/platforms/aks.jsonnet, manifests/platforms/gke.jsonnet, manifests/tests/aks.jsonnet, manifests/tests/gke.jsonnet
With Google-based Oauth, we need to additionally restrict the user in
some way - we don't want to allow just _any_ Google account to access
the prometheus/kibana consoles.
This change adds a *required* flag to specify a Google email domain,
and oauth2 proxy will only allow Google users from this domain.
NB: This effectively restricts kubeprod to only supporting GSuite
accounts (@gmail.com is not useful), which is conceptually similar to
the AKS setup which allows only members from a particular Azure
tenant.  Allowing a whitelist of specific (non-GSuite) Gmail accounts
instead is probably desirable, but postponed for a future change.
=> GKE: Restrict Oauth authentication by domain suffix

docs/release_process.md
The release branches are protected and require commits to be signed.
=> docs: cherry-picked commits should be signed and verified

docs/quickstart-aks.md, docs/quickstart-gke.md
This will default to the latest *release* available of kubeprod. By the moment it will be set to:
```
~/projects/kube-prod-runtime$ echo $BKPR_VERSION
v0.3.1
```
Let me know what you think :)
=> Get kubeprod latest release programatically in quickstart guides

Makefile
Since we now enforce squashed merges the regex to discover merges
from git commit logs needed to be tweaked.
=> update regex to fix PR discovery from git logs

manifests/components/prometheus.jsonnet
This PR updates Prometheus to the latest available version deployed by Bitnami.
Based on the [Prometheus changelog](https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md#240--2018-09-11) in the `2.4.0` version the WAL implementation was re-written, so the storage is not forward compatible.
Prometheus 2.3 storage will work on 2.4 but not vice-versa.
Tested this upgrade manually in Kubeprod changing the statefulset to point to the latest version of Prometheus in my dev environment and didn't face any issue, the update was successfully.
None of the rest of changes of newer versions of Prometheus affect to the current configuration we have in kubeprod. 
Reference: https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md#240--2018-09-11
=> Update Prometheus to 2.4.3

docs/release_process.md
fixes typo's in release candidate naming
=> docs: fix typos in release_process.md

Jenkinsfile, Makefile, kubeprod/Makefile, kubeprod/cmd/install.go, kubeprod/cmd/root.go, kubeprod/cmd/version.go, kubeprod/main.go, kubeprod/pkg/installer/install.go, kubeprod/pkg/prodruntime/manifest.go
Make the `kubeprod install --manifests` flag default to a URL derived
from the git tag/sha used at build-time.  This should "just work" in
most situations.
Fixes #212
=> Change `--manifests` default to point to versioned github URL

Jenkinsfile, Makefile, kubeprod/Makefile, kubeprod/cmd/install.go, kubeprod/cmd/root.go, kubeprod/cmd/version.go, kubeprod/main.go
=> Upload release manifests to S3 bucket

Jenkinsfile
`failFast: true` allows us to terminate a CI job as soon as a failure is encountered in parallel tasks
=> ci: set failFast to true in parallel tasks

docs/install.md, docs/quickstart-aks.md, docs/quickstart-gke.md
Removes `--manifests` flag from quickstart guides
=> docs: removes use of `--manifests` flag from quickstarts

README.md
fixes quickstart link from kubeless.io
=> docs: add quickstart section back to the readme

Jenkinsfile
We can no longer provision K8s 1.9 clusters on GKE.
=> ci: remove tests on gke 1.9

README.md, manifests/components/cert-manager.jsonnet
Bumps cert-manager to v0.5.2, which contains a patch to prevent excessive usage of the Let's Encrypt API under certain conditions. More information on this can be found in our release notes 😄 
This also updates the README.md to reflect the actual 'state of the world'!
=> Bump cert-manager to v0.5.2

manifests/components/cert-manager.jsonnet, manifests/components/elasticsearch.jsonnet, manifests/components/externaldns.jsonnet, manifests/components/fluentd-es.jsonnet, manifests/components/grafana.jsonnet, manifests/components/kibana.jsonnet, manifests/components/nginx-ingress.jsonnet, manifests/components/oauth2-proxy.jsonnet, manifests/components/prometheus.jsonnet, manifests/components/versions.json
This should make release engineering and automated updates of
image versions easier.
Also, bump versions for:
* cert-manager
* external-dns
=> Keep all image versions in a single JSON file.

bors.toml
Integration tests take an unusually long time with this project, so we
want a bot to take approved PRs, do a final rebase and test, and only
_then_ merge if there are no issues.
TL;DR: Type `bors r+` on a line by itself to say "PR should be merged".
See https://bors.tech/documentation/ for other supported bot commands.
=> Enable bors-ng

docs/migration-guides/prometheus-migration.md
and expose prometheus-rsync service.
Some minor Markdown lint fixes too. 
I guess we can add the service as part of the `kubeprod-manifests.jsonnet` modifications, but I tried to make it easy to understand by the final user as an explicit step on the procedure.
=> Added instructions for clean  up the sidecar container 

docs/quickstart-gke.md
The user should specify the GCE zone (not region). Corrected this
mistake and also renamed the variable to `GCLOUD_ZONE`.
Fixes #285
=> docs: rename quickstart env var `GCLOUD_REGION` to `GCLOUD_ZONE`

manifests/components/prometheus.jsonnet
Significantly newer version than our previous ancient 1.0.
Fixes #85 and many other minor issues.
=> Upgrade addon-resizer to 1.8.4

Jenkinsfile
We only support 1.10-1.11 on release-1.1 (and newer).  No longer test
on 1.9.x as well.
=> Drop AKS 1.9.x from testing matrix

tests/monitoring_test.go
Previously we just checked for exactly 3 timeseries.  This failed if
an elasticsearch pod restarted during the testing period, despite this
being an expected and ok event.
Replace with a more explicit check for each of
`kubernetes_pod_name=elasticsearch-logging-[012]` (and ignore any
duplicates or additional matches).
Fixes #310
=> More robust check for elasticsearch timeseries

Jenkinsfile
CI builds are failing since k8s 1.10.8 is no longer available in AKS.
=> CI: Update AKS version test cluster setup

manifests/components/externaldns.jsonnet
Previously ExternalDNS stored a TXT record alongside each managed DNS
record, to avoid stomping on DNS entries that were created
elsewhere (good).
These TXT records conflicted with CNAME records, since they had the
same name (bad).
Configure ExternalDNS to store the TXT record in a different name.
Now the TXT metadata record for `foo` will be stored as
`_externaldns.foo`.
=> ExternalDNS: Track provenance in non-conflicting TXT name

Dockerfile, Jenkinsfile
The PR adds a Dockerfile for building a kubeprod docker image from the
specified BKPR release version. Kaniko is used to build the image in
jenkins and publish it at `kubeprod/kubeprod` on docker hub
Note: only release versions are available as docker images
Closes #185
=> Build and published kubeprod release image at kubeprod/kubeprod

Jenkinsfile
It seems `gcloud` cannot create GKE clusters running Kubernetes 1.10
currently.
=> Fix GKE tests

Jenkinsfile
https://cloud.google.com/kubernetes-engine/release-notes#february-18-2019
```
Versions no longer available
The following versions are no longer available for new clusters or
upgrades to existing cluster masters:
1.10.x
```
This means GKE currently _only_ supports 1.11.x (masters) :/
=> GKE no longer supports 1.10

manifests/components/externaldns.jsonnet
This is an improvement/fix to #343, to achieve the originally stated
goal.  external-dns prepends _exactly_ the txt-prefix to created TXT
metadata records, so the `.` separator needs to be added explicitly.
=> external-dns: Add trailing '.' to txt-prefix

Jenkinsfile, tests/ingress_test.go
This PR sets up the Jenkins job to run on a single agent node. The advantages of this change are:
- jenkins resource requirements is greatly reduced
- job is executed to completion once it is assigned a agent
- failing integration tests are retried up to 3 times
- tests are noticeably faster!
=> ci: refactored Jenkinsfile to run job on a single agent node

manifests/components/nginx-ingress.jsonnet, manifests/components/oauth2-proxy.jsonnet, manifests/lib/utils.libsonnet
nginx-ingress and oauth2_proxy are expected to be in the serving path,
and so should be redundant to single-machine failure (as per the BKPR
default HA target).
Accordingly:
- increase replicas for each to 2
- add (weak) host anti-affinity
- configure a `PodDisruptionBudget` that ensures at least 1 replica of
each is healthy before draining a node.
Fixes #373
=> Increase nginx-ingress + oauth2_proxy to replicas=2

docs/migration-guides/bkpr-1.2-migration-guide.md, docs/quickstart-gke.md, kubeprod/pkg/aks/platform.go, kubeprod/pkg/eks/platform.go, kubeprod/pkg/gke/platform.go, manifests/components/kibana.jsonnet, manifests/components/nginx-ingress.jsonnet, manifests/components/oauth2-proxy.jsonnet, manifests/lib/utils.libsonnet, manifests/platforms/aks.jsonnet, manifests/platforms/eks.jsonnet, manifests/platforms/gke.jsonnet, tests/ingress_test.go, tests/vendor/github.com/pusher/oauth2_proxy/LICENSE, tests/vendor/github.com/pusher/oauth2_proxy/cookie/cookies.go, tests/vendor/github.com/pusher/oauth2_proxy/cookie/nonce.go, tests/vendor/vendor.json
Improve the oauth2_proxy setup to be able to protect Ingress objects
from other k8s namespaces too.
This change will protect any Ingress, provided it:
a) uses a hostname within the zone managed by BKPR, and
b) includes the required Ingress annotations (see below).
The key changes involve:
- oauth2_proxy (encrypted) cookie is now exposed to the full DNS
zone given by `--dns-zone`
- Upstream identity provider setup is simplified to only redirect to
https://auth.${dns_zone}/oauth2/callback
- oauth2_proxy setup is modified to perform redirects to any host
within ${dns_zone}
To protect your Ingress with the BKPR-managed oauth2 stack, your
Ingress requires the following annotations (with `${dns_zone}`
replaced accordingly. Note other $... strings should remain as-is).
If using jsonnet, deriving …
=> Allow oauth2_proxy to be used from other namespaces

Jenkinsfile
The GITHUB_USER in the release stage should be set to `bitnami`, the
github org under which the project is hosted.
=> ci: fix github publishing in release stage

README.md, docs/FAQ.md, docs/install.md, jenkins/Release_Notes.md.tmpl
Adds missing references to EKS platform support and quickstart docs
=> docs: update references to Amazon EKS quickstart

manifests/components/oauth2-proxy.jsonnet, manifests/lib/utils.libsonnet, manifests/platforms/aks.jsonnet, manifests/platforms/eks.jsonnet, manifests/platforms/gke.jsonnet, tests/ingress_test.go
Add new `HashedConfigMap` and `HashedSecret` derived objects that
modify their `metadata.name` based on a hash of `self.data`.
Change external-dns and oauth2_proxy `Secret`s to `HashedSecret`,
which will force a `Deployment` update whenever the contents (name) of
the referenced `Secret` changes.
Going forward, we should use this pattern for any processes that don't
re-read a modified mounted file and use a configmap/secret that is
static after creation.
Fixes #64
=> Update deployment when ext-dns or oauth2_proxy secret changes

Jenkinsfile
kaniko does not appear to pick docker hub credentials placed at
`/root/.docker/` anymore. As a result the release stage was not able to
push images to the docker registry. In this PR we explicitly specify the
path to the docker `config.json` file in the `DOCKER_CONFIG` variable.
We've also updated the kaniko version in this PR.
=> ci: specify `DOCKER_CONFIG` env variable for kaniko

Jenkinsfile
Retrying failed build stages 3 times is excessive and wasteful in most
cases. To account for transient cluster creation failures, one
additional retry should be sufficient to overcome issues coming from
cluster creation issues.
Additionally we have added a 3 minute wait before retrying.
=> ci: retry failed stages only once after a failure

Jenkinsfile
While install BKPR in the CI pipeline, we have been seeing the error message `Error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request`. 
It appears  the error is encountered because we're trying to install BKPR before the API server is READY. To workaround this issue, we now wait 60s after the rollout of deployments and statefulsets in the `kube-system` namespace are completed.
=> CI: fix kubeprod install errors in the CI pipeline

docs/components.md, manifests/components/grafana.jsonnet
I was missing the guide to customise the Grafana provisioned dashboards, so it is added here.
Also, feedback that @anguslees gave me in #500 has been applied here.
I'm still thinking on a good way to test the Grafana dashboards, will come with another PR with more improvements :) 
Cheers
=> feat: Add customize guide for Grafana provisioned dashboards and add code improvements to components/grafana.jsonnet

tests/monitoring_test.go
The exporters can take some time to scrape data.
=> tests: retry Exporters tests on failures

manifests/components/externaldns.jsonnet
ref: https://github.com/kubernetes-incubator/external-dns/issues/990
=> manifests: updated RBAC permissions for external-dns

Jenkinsfile
the `kversion` variable was not being properly bound because of closures as a result of
which the wrong k8s version was being picked for the aks tests
=> ci: fix aks k8s version selection

Jenkinsfile
It has been observed `cluster delete` generally takes less than 5 mins to successfully delete the cluster. Another observation is when it takes more than 5 mins, the deletion will fail. So waiting 20mins (default) here is a big waste of time.  I've lowered it to a 10mins instead.
=> ci: ignore cluster deletion errors for EKS

tests/ingress_test.go, tests/logging_test.go, tests/monitoring_test.go
Successful passes of the ci tests generally conclude in 5 - 10mins. It has been observered that
when it takes longer the tests are bound to fail. Some of our tests use 30m retry timeouts
which is lot of time wasted hoping that a failing test will pass.
This commit optimizes the retry timeouts for all tests to more realistic values thereby reducing
the time spent by a job in the CI environment
=> tests: optimize retry timeouts

Jenkinsfile, tests/ingress_test.go, tests/logging_test.go, tests/monitoring_test.go
Backported:
b5859ca - tests: optimize retry timeouts
705ec25 - tests: [fix] retry monitoring/exporters test
a8d901e - ci: ignore cluster deletion errors for EKS
d1fcdcb - ci: fix aks k8s version selection
422d434 - tests: retry Exporters tests on failures
=> [ci/backports/1.2] backport ci updates

docs/application-developers-reference-guide.md
Signed-off-by: juan131 <juan@bitnami.com>
The annotations suggested to allow Prometheus collecting metrics from a service's endpoints are wrong since the `prometheus.io/metrics` annotation is not used to set the path. 
This PR sets the right annotation (`prometheus.io/path`) in the instructions.
=> Update instructions to add application monitoring via Prometheus

jenkins/automation/functions
The `status/waiting-for-review` label blocks the CI from building the PR's allowing
project maintainers to review the changes before they are picked up by the CI.
=> ci: apply `status/waiting-for-review` to automated component update PRs

manifests/components/grafana.jsonnet
To apply any configuration updates to grafana the Pods need to be restarted.
To achieve this we changed grafana `ConfigMaps` to  `HashedConfigMap` which will
force the Pod update whenever the contents of the reference `ConfigMap` changes.
=> manifests: reload grafana pods on ConfigMap updates

docs/components.md, manifests/components/grafana.jsonnet
the `plugins` array would allow users to easily install plugins to grafana using jsonnet overrides,
f.e. the following jsonnet overlay for grafana will install the listed plugins when applied
```
{
plugins:: [
"grafana-piechart-panel",
"grafana-worldmap-panel",
],
}
```
=> manifests: define grafana plugins array

manifests/components/grafana.jsonnet
- manifests: reload grafana pods on ConfigMap updates
- manifests: define grafana plugins array
=> [backports/1.2/manifests] backported changes to manifests

docs/components.md, manifests/components/kibana.jsonnet
This pull requests adds support for a very rudimentary mechanism to install additional Kibana plug-ins via an init container.
https://github.com/bitnami/kube-prod-runtime/issues/453
=> Support for installing Kibana plug-ins

Jenkinsfile, manifests/Makefile, manifests/components/cert-manager.jsonnet, manifests/components/elasticsearch.jsonnet, manifests/components/externaldns.jsonnet, manifests/components/fluentd-es.jsonnet, manifests/components/grafana.jsonnet, manifests/components/kibana.jsonnet, manifests/components/nginx-ingress.jsonnet, manifests/components/oauth2-proxy.jsonnet, manifests/components/prometheus-config.jsonnet, manifests/components/prometheus.jsonnet, manifests/components/version.jsonnet, manifests/lib/kube.libsonnet, manifests/lib/utils.libsonnet, manifests/tests/aks.jsonnet, manifests/tests/eks.jsonnet, manifests/tests/gke.jsonnet
Add `Makefile` support for running and enforcing `jsonnet fmt` style
against our jsonnet files.
`make -C manifests fmttest` does a read-only verification.  This is
now called from `Jenkinsfile` to enforce style compliance.
`make -C manifests fmt` will update files in-place to follow the style
guide.
Fwiw, the current change (and jenkins config) will use `jsonnet`
0.12.1.  There have been minor `fmt` style deviations over the history
of `jsonnet`.
=> Enforce a jsonnet fmt style

Dockerfile
- base kubeprod docker image on bitnami/minideb:stretch
(cherry picked from commit 22d92dddc18857e089f618242cdfbd1e4aea386d)
=> [backports/release-1.2] backport changes to 1.2. branch 

Dockerfile
(cherry picked from commit 22d92dddc18857e089f618242cdfbd1e4aea386d)
=> base kubeprod docker image on bitnami/minideb:stretch

Jenkinsfile
ci: set securityContext of kubectl container to root
(cherry picked from commit 2cf43d5a21ebdd0fef30c9ec571f8f0f4a95425b)
=> [backports/release-1.2] backport ci updates

Jenkinsfile
ci: set securityContext of kubectl container to root
(cherry picked from commit 2cf43d5a21ebdd0fef30c9ec571f8f0f4a95425b)
=> [backports/release-1.3] backport ci updates

Jenkinsfile
The github-integration plugin provides nice features that allow us to control the
behaviour of CI using github comments and labels. However we have been noticing issues
where build on branches and tags are randomly triggered.
To work around this issue, we are switching to processing only tags using this plugin while
processing branches and tags with the regular jenkins github integration.
=> ci: use github-integration plugin for PR's only

Jenkinsfile
eksctl 0.1.38:
- supports k8s versions 1.10, 1.11, 1.12, 1.13
- use's newer AMI's that have fixed the max fds issue
=> ci: use eksctl version 0.1.38

Jenkinsfile
ci: fix builds (#643)
* ci: mount `/home/jenkins` in pod containers
ref: https://support.cloudbees.com/hc/en-us/articles/360000304932-Pipeline-jobs-fail-to-run-in-a-Docker-in-Docker-step
* ci: update pod container images
(cherry picked from commit a7f8592c6a23c478bf6ebc955878b32f780470a2)
=> [backports/ci/1.2] backport ci updates

Jenkinsfile
ci: fix builds (#643)
* ci: mount `/home/jenkins` in pod containers
ref: https://support.cloudbees.com/hc/en-us/articles/360000304932-Pipeline-jobs-fail-to-run-in-a-Docker-in-Docker-step
* ci: update pod container images
(cherry picked from commit a7f8592c6a23c478bf6ebc955878b32f780470a2)
=> [backports/ci/1.3] backport ci updates

manifests/components/externaldns.jsonnet
=> external-dns: set `log-level=warning`

manifests/components/nginx-ingress.jsonnet
Oauth authentication of AKS was failing after the oauth2_proxy 4.1.0 update (#671) with the error
`upstream sent too big header while reading response header from upstream` in the nginx-ingress logs.
=> [manifests/nginx-ingress] set `proxy-buffer-size` to `16k`

Jenkinsfile
ref: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
=> ci: Use the Authorization HTTP header for GitHub API queries, as using the `access_token` query parameter is deprecated

manifests/components/externaldns.jsonnet
This allows BKPR users to create DNSEndpoints using the YAML files and kubectl
fe.
```yaml
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
name: my-subdomain
spec:
endpoints:
- dnsName: "my-subdomain.my-domain.com."
targets:
- "172.217.163.196"
recordType: A
recordTTL: 10
```
=> manifests/edns: add `crd` to edns sources

Jenkinsfile, README.md
* all 3 platforms now tested for 1.15 and 1.16 (GA on all),
using 1.16 also for `generic`
* use same lock for `generic` and `gke` as they are both using
GKE, this seems to have been the cause of flaky e2e testing results
* pin ginkgo CLI build to match `go mod` in `tests/`
* workaround https://issues.jenkins-ci.org/browse/JENKINS-41929
to avoid the need for "2nd job run" when releases to test were changed
from parameters properties (else it's results are confusing as they
would stick to previous settings)
=> [jjo] feat: all clouds tested for 1.15-1.16, fix integration tests

manifests/components/nginx-ingress.jsonnet
Fixes #815.
The increased size of headers required for auth fails
on Safari with default `http2-max-field-size` and
`http2-max-headers-size`, adjust their values.
=> fix: increase nginx-ingress header/field sizes

manifests/Makefile
Adapt manifests/Makefile to support older/current jsonnet releases,
eases local testing while not requiring an atomic update on our
jenkins-bkpr pipeline.
Note that this small change will need to be backported into active
releases branches, to let jenkins-bkpr use newer jsonnet binaries.
=> [jjo] fix: support newer jsonnet / jsonnetfmt

Jenkinsfile, manifests/components/fluentd-es-config/output.conf, manifests/components/images.json
Fixes #878.
Elasticsearch > 7.7 deprecated `type_name`, triggering
log-spam from fluentd, use `suppress_type_name true`
with updated fluentd image.
FYI successfully dogfood-ed internally in our clusters,
to verify no logspam from fluentd, we may later want to
add a test on this (i.e. clean / empty? fluentd logs).
=> [jjo] fix: use fluentd suppress_type_name

manifests/components/grafana.jsonnet
Fix grafana.jsonnet dashboard imports to use full vendored
path instead of symlink, as the latter is not present at
`releases.kubeprod.io` cloudfront bucket (we ignore symlinks
when pushing manifest tree from src to the s3 bucket).
=> [jjo] fix grafana dashboard imports

manifests/components/images.json
Fixing bitnami/bitnami-docker-fluentd#11 for BKPR, withdraws #897.
=> [jjo] fix: update fluentd image for bitnami/bitnami-docker-fluentd#11

manifests/components/externaldns.jsonnet, manifests/components/images.json
Fixes #911 
Add `endpoints` to external-dns r/only RBAC perms (see https://github.com/kubernetes-sigs/external-dns/blob/master/kustomize/external-dns-clusterrole.yaml), required since 0.7.2.
=> [jjo] fix: add `endpoints` to external-dns RBAC r/only perms

manifests/components/grafana.jsonnet, manifests/platforms/aks.jsonnet
Fix #915.
* oauth2-proxy >= 6.0.0 on AKS doesn't provide 
"X-Auth-Request-User" header on AKS, used by grafana
to auto-login users, use "X-Auth-Request-Email" instead
=> [jjo] fix: oauth2-proxy >= 6.0.0 and grafana on AKS

Jenkinsfile, README.md, jenkins/cloud-custodian/Jenkinsfile
* move supported Kubernetes releases to 1.16,1.17 later
to be merged into release-1.7 branch
* update README.md likewise, also removing old BKPR
releases from images versions table
=> [jjo] move support window to 1.16,1.17 on all clouds

Jenkinsfile, README.md, jenkins/cloud-custodian/Jenkinsfile
=> [jjo] release-1.7: move support window to 1.16,1.17 on all clouds (merge #921 from master)

jenkins/cloud-custodian/Jenkinsfile, jenkins/cloud-custodian/policies/aws.yaml
We were using a Cloud-Custodian release from January.
This PR updates the Custodian default version the Jenkins pipeline uses to clean-up the leftovers after the continuous testing execution.
Tests result:
```
Running the AWS Cloud Custodian policies
[Pipeline] sh
2020-09-17 09:55:36,050: custodian.policy:INFO policy:bkpr-delete-cft-stacks resource:cfn region:us-east-1 count:50 time:0.46
2020-09-17 09:55:54,755: custodian.policy:INFO policy:bkpr-delete-cft-stacks action:delete resources:50 execution_time:18.70
2020-09-17 09:55:56,031: custodian.policy:INFO policy:bkpr-delete-eks-clusters resource:aws.eks region:us-east-1 count:8 time:1.27
2020-09-17 09:55:59,089: custodian.policy:INFO policy:bkpr-delete-eks-clusters action:delete resources:8 execution_time:3.06
2020-09-17 09:56:01,048: …
```
=> Feat: Update the default Cloud Custodian version for BKPR to 0.9.6.0 // Improve AWS policies

Jenkinsfile
We have a high amount of jobs that are failing because of timeout errors. This PR tries to bump this value as suggested by @jjo https://github.com/bitnami/kube-prod-runtime/pull/930#issuecomment-692666778
=> Increase timeout of the Jenkins job

jenkins/cloud-custodian/Jenkinsfile, jenkins/cloud-custodian/policies/aws.yaml, jenkins/cloud-custodian/policies/google.yaml
We have been facing some more issues related with the clean-ups in AWS related to the AWS dependency errors. 
This means that if you want to delete a VPC you must delete before:
* EC2 instances
* Security groups
* NatGateways
* Elastic IP addresses
* InternetGateways
Otherwise the AWS API will throw a dependency error.
In this PR you will also see that I am setting the 0.9.6.2 version of the Cloud-Custodian container. This version contains the latest improvements I landed in the Cloud-Custodian repository **and the `detach` operation coded for the InternetGateway**, as it is required prior deleting the VPC.
I will contribute to the project with that operation, but I wouldn't like to block all the clean-ups in the meantime.
****
Apart from the fix of the AWS policies (for hostedzones / IAM …
=> Fix: Update Custodian version to custom Bitnami container and fix/improve AWS / Google policies

Jenkinsfile
932: Increase timeout of the Jenkins job r=jjo a=javsalgar
We have a high amount of jobs that are failing because of timeout errors. This PR tries to bump this value as suggested by @jjo https://github.com/bitnami/kube-prod-runtime/pull/930#issuecomment-692666778
Co-authored-by: Javier J. Salmerón-García <jsalmeron@bitnami.com>
=> [release-1.7] Increase timeout of the Jenkins job

Jenkinsfile
This commit removes the usage of a proxy for web traffic from the
containers inside the podTemplate. The URL is specifying a deployment in
the webcache namespace in the AWS-int cluster. This is a piece of
infrastructure that we do not intend to maintain.
It's not clear what value the proxy was providing to the pipeline. The
Manifest stage completes in a couple minutes. The current platform tests
are failing for OAuth/TLS issues that are likely not related to the
proxy.
If this impacts other portions of the pipeline in clear and obvious
ways, we'll look at fixing those problems without reintroducing the
proxy.
This has been tested in multiple different ways. See the task for
further details.
https://phabricator.nami.run/T39254
=> Remove dependency on squid deployment
