tests/junit/junit_1.xml, tests/junit/junit_2.xml, tests/junit/junit_3.xml, tests/junit/junit_4.xml
found some more files that were committed which should not have been
=> removed accidentally committed `tests/junit` folder

Jenkinsfile, tests/monitoring_test.go
=> GKE: Enable integration tests

kubeprod/Makefile
see https://github.com/mholt/archiver/pull/99
=> archiver tool has been renamed to `arc`

README.md, docs/install.md, docs/quickstart-aks.md, docs/quickstart-gke.md, jenkins/Release_Notes.md.tmpl
Installation/Build guide for `kubeprod` installer
Closes #204
=> docs: adds install/build guide

kubeprod/cmd/install.go, kubeprod/cmd/version.go
=> Improve kubeprod error messaging on kubectl config errors

Jenkinsfile
Basically makes the tests complete faster because we parallelize :slightly_smiling_face:
=> bump up parallelism of ginkgo tests

docs/application-developers-reference-guide.md
=> docs: adds instuction manual for app authors targetting BKPR

manifests/components/nginx-ingress.jsonnet
This PR upgrades NGINX ingress controller to version 0.21 from version 0.19, and also removes the default-http-backend which is not required since 0.20.
Fixes #249.
=> Upgrade to NGINX ingress controller 0.21.

kubeprod/pkg/gke/platform.go
=> Better explanation on failure to set IAM policy for GKE.

docs/kubeapps-on-bkpr.md, docs/quickstart-aks.md, docs/quickstart-gke.md, docs/troubleshooting.md
Adds information on steps to perform while troubleshooting DNS related issues
=> docs: troubleshooting dns issues

Jenkinsfile, docs/quickstart-aks.md, docs/quickstart-gke.md, manifests/components/elasticsearch.jsonnet
=> Add support for k8s 1.11 clusters

README.md, docs/FAQ.md, docs/roadmap.md
Expand/update as needed.
Fixes #194
=> Add basic roadmap document

docs/quickstart-gke.md
=> Specify the project ID is needed

manifests/components/externaldns.jsonnet, manifests/platforms/eks.jsonnet
Add manifest(s) to support EKS on AWS.
=>  Initial support for EKS manifests

jenkins/automation/Jenkinsfile, jenkins/automation/automatic-updates.sh, jenkins/automation/functions
This PR automates the creation of pull-requests for updating the component images in BKPR. The script scans the master branch and the last to release branches and performs a lookup on docker hub to check for image updates. If a new image update is available, a PR is created for that update and submitted for review by the BKPR maintainers.
A new CI job needs to be added to the Jenkins setup that will execute this script periodically. The `Jenkinsfile` added in the PR describes the job
=> automation: infrastructure to automate BKPR component updates

Jenkinsfile
For a given k8s series (MAJOR.MINOR), We now query the AKS API and use the
most recent PATCH release available of the specified version series.
=> ci: automatically use latest k8s PATCH versions for AKS test clusters

Jenkinsfile
It has been observed when there are a lot of parallel jobs in the
jenkins queue, jenkins does not appear to node assignments based on FIFO
basis. This results in the jobs taking a really long time to complete
(courtesy the AKS start up time).
Since the GKE clusters come up quickly, so do the tests complete faster.
This PR is a workaround to prioritize testing on GKE clusters so that
problematic PR's fails faster in such cases
=> ci: prioritize testing on GKE over AKS

Jenkinsfile
The `kaniko` container was incorrectly being launched from the `go`
container context.
=> ci: fixes publishing docker images during the release

manifests/components/images.json, manifests/lib/utils.libsonnet
- https://github.com/bitnami/kube-prod-runtime/pull/388
- https://github.com/bitnami/kube-prod-runtime/pull/355
=> release-1.1: backported changes

Jenkinsfile, bors.toml, manifests/components/elasticsearch.jsonnet, manifests/components/kibana.jsonnet
Elasticsearch and Kibana updated to address security vulnerabilities
ref: https://discuss.elastic.co/t/elastic-stack-6-6-1-and-5-6-15-security-update/169077
=> [maintenance/release-1.0] Updates Elasticsearch and Kibana versions

bors.toml
Define list of PR labels that blocks a PR from being merged when it is r+-ed.
=> bors: define block labels

manifests/Makefile, manifests/contrib/helpers.jsonnet, manifests/contrib/helpers_unit_test.jsonnet, manifests/contrib/helpers_usage_test.jsonnet, manifests/contrib/showtree.jsonnet
See `contrib/helpers_usage_test.jsonnet` for example usage.
=> [jjo] add contrib/helpers.jsonnet, including unit tests

docs/quickstart-aks.md, docs/quickstart-eks.md, docs/quickstart-gke.md
various improvements and fixes to the quickstart docs
=> docs: improvements to the quickstart guides

Jenkinsfile
fixes typo in docker image repo name
=> ci: fix docker push repo name

Jenkinsfile
=> ci: adds ownership tags to cluster resources

Jenkinsfile
Also raised the overall timeout by 30 mins to accomodate this timeout.
=> ci: adds 20 min timeout for debugging broken tests

Jenkinsfile
Backports the following PR's to release-1.1
- #456 
- #457 
- #462
=> [backports/ci/1.1] backport fixes to release-1.1 branch

Jenkinsfile
Backports the following PR's to release-1.2
- #456 
- #457 
- #462
=> [backports/ci/1.2] backport fixes to release-1.2 branch

Jenkinsfile
- begin testing against k8s 1.12
=> K8s 1.12 support

Jenkinsfile
We plan to switch to using the [github-integration](https://plugins.jenkins.io/github-pullrequest) 
plugin to handle the ci integration with github. This is mainly because the plugin allows us to 
configure behaviour of the pipeline based on github comments, labels and so on.
However there are some shortcomings of the plugin when configured for use with a multibranch jenkins 
pipeline, namely:
- errors out while configuring the git clone operation
- commit build status is not updated on github
This PR aims to workaround these two issues
=> ci: configure ci job to integrate with github-integration plugin for Jenkins

docs/components.md, manifests/components/grafana.jsonnet
- manifests: reload grafana pods on ConfigMap updates
- manifests: define grafana plugins array
=> [backports/1.3/manifests] backported changes to manifests

manifests/components/images.json
```
bitnami/elasticsearch:6.7.1-r2 -> bitnami/elasticsearch:6.8.0-r31
bitnami/kibana:6.7.2-r1 -> bitnami/kibana:6.8.0-r29
```
=> components: update elasticsearch and kibana to 6.8.x release series

Dockerfile
(cherry picked from commit 61d4bc581ed2da8a98970ea1a3d94b6a0e6def3e)
=> dockerfile: fix image build with kaniko (#578)

docs/migration-guides/prometheus-migration.md, manifests/components/elasticsearch.jsonnet
Signed-off-by: Sameer Naik <sameer@bitnami.com>
(cherry picked from commit 435a449c90963778dbfd3a81396ed793ed849dee)
=> [backports/manifests/1.2] Replace Alpine by minideb as base image

docs/migration-guides/prometheus-migration.md, manifests/components/elasticsearch.jsonnet
Signed-off-by: Sameer Naik <sameer@bitnami.com>
(cherry picked from commit 435a449c90963778dbfd3a81396ed793ed849dee)
=> [backports/manifests/1.3] Replace Alpine by minideb as base image

Jenkinsfile
The github-integration plugin provides nice features that allow us to control the
behaviour of CI using github comments and labels. However we have been noticing issues
where build on branches and tags are randomly triggered.
To work around this issue, we are switching to processing only tags using this plugin while
processing branches and tags with the regular jenkins github integration.
(cherry picked from commit e019cadbe05fd469d49fc7bb1a2f039b0127c0ff)
=> [backports/ci/1.3] ci: use github-integration plugin for PR's only

Jenkinsfile
The github-integration plugin provides nice features that allow us to control the
behaviour of CI using github comments and labels. However we have been noticing issues
where build on branches and tags are randomly triggered.
To work around this issue, we are switching to processing only tags using this plugin while
processing branches and tags with the regular jenkins github integration.
=> [backports/ci/1.2] ci: use github-integration plugin for PR's only

Jenkinsfile
Initial steps to add k8s 1.14 support to BKPR
=> ci: test BKPR on k8s 1.14

Jenkinsfile
=> ci: do not pause the job for debugging

Jenkinsfile, manifests/components/cert-manager.jsonnet, manifests/components/crds/cert-manager.yaml, manifests/components/images.json, tests/ingress_test.go
Closes #669
Signed-off-by: Bitnami Containers <containers@bitnami.com>
Signed-off-by: Sameer Naik <sameersbn@vmware.com>
(cherry picked from commit 14ae95c6e7c158e62b8af547e7c3b609be22ac08)
=> [backport/1.3] cert-manager: component image updated to 'bitnami/cert-manager:0.12.0-r29'

manifests/components/images.json
=> use bitnami/configmap-reload image for config_reload containers

manifests/components/images.json, manifests/components/prometheus.jsonnet, tests/testdata/prometheus-crashloop-alerts.jsonnet
- switched to bitnami/kube-state-metrics image
- moved image definition to images.json
- fixed monitoring tests
- closes #654
=> [manifests] update kube-state-metrics to version 1.9.0

docs/quickstart-aks.md, docs/quickstart-eks.md, docs/quickstart-gke.md
=> docs: link to app developers guide from the quickstart guides

docs/application-developers-reference-guide.md
=> docs: document oauth2 annotations in application developers guide

Jenkinsfile, docs/quickstart-aks.md, docs/quickstart-eks.md, docs/quickstart-generic.md, docs/quickstart-gke.md
=> [jjo] fix: improve kubeprod removal (e2e and docu)

Jenkinsfile, jenkins/cloud-custodian/Jenkinsfile
Signed-off-by: David Barranco <dbarranco@vmware.com>
=> Feat: Update GKE versions
